workspace()
include("GPUStart.jl")
StartCode()
t = Tensor([1,1,28,28])
f = Filters([20,1,5,5])
c = Convolution(t,f)
net = EndCode()
net.value[t] = rand(140,140)
net.value[f] = rand(5,5)
net = compile(net)
net = convert(net,"GPU")
ADforward!(net)