workspace()
include("GPUstart.jl")
StartCode()
A = ADVariable()
X = ADVariable()
out = sum(A*X)
net = EndCode()
net.value[A] = rand(2,2)
net.value[X] = rand(2,1)
CUDArt.init([0])
net = compile(net,backend="GPU")
ADforward!(net)
#ADbackward!(net)