workspace()
include("ArrayFire.jl")
afVersion()
backend = availableBackends()
setBackend(backend["opencl"])
afInfo()
getDevice()
n = rand(Float32,5000,5000)
m = rand(Float32,5000,5000)
@time n*m
l = AFArray(n)
r = AFArray(m)
@time matmul(l,r)
#to_host(f)