workspace()
include("ArrayFire.jl")
afVersion()
backend = availableBackends()
setBackend(backend["CPU"])
n = rand(4,4)
m = rand(4,4)
println(n*m)
l = AFArray(n)
r = AFArray(m)
f = matmul(l,r)
to_host(f)